/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRO1041.FORM;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author phamt
 */
public class DangNhap extends javax.swing.JFrame {
     String username="sa";
     String password="123";
     String url="jdbc:sqlserver://localhost:1433;databaseName=QL_NhaXe";
    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_dangnhap = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 150));

        jPanel1.setLayout(null);

        btn_dangnhap.setBackground(new java.awt.Color(204, 204, 255));
        btn_dangnhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_dangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login.png"))); // NOI18N
        btn_dangnhap.setText("Đăng Nhập");
        btn_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhapActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dangnhap);
        btn_dangnhap.setBounds(220, 230, 150, 40);

        btn_thoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_thoat);
        btn_thoat.setBounds(390, 230, 120, 40);

        txt_username.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_username);
        txt_username.setBounds(230, 110, 260, 30);
        jPanel1.add(txt_pass);
        txt_pass.setBounds(230, 160, 260, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/QR.png"))); // NOI18N
        jPanel1.add(jButton1);
        jButton1.setBounds(610, 100, 130, 160);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Hoặc");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(520, 110, 80, 80);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 153));
        jLabel6.setText("Mật khẩu :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 160, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("Tài khoản :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 110, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 204));
        jLabel2.setText("Đăng Nhập");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 0, 310, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Bokeh-effect.gif"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhapActionPerformed
         if(txt_username.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Username không được để trống");
            txt_username.requestFocus();
            return;
        } else if(txt_pass.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Password không được để trống");
            txt_pass.requestFocus();
            return;
        }
        else{
            Connection con = null;
            Statement stmt = null;
            try{
                con=DriverManager.getConnection(url,username,password);
                stmt = con.createStatement();
                String sql = "select Username, PassWords, ChucVu from TaiKhoan";
                ResultSet rs = stmt.executeQuery(sql);
                String user, pass, chucvu;
                boolean flag = false;
                while(rs.next()){
                    user = rs.getString("Username");
                    pass = rs.getString("PassWords");
                    if(user.equals(txt_username.getText()) && pass.equals(txt_pass.getText())){
                        flag =true;
                        chucvu = rs.getString("ChucVu");
                        if(chucvu.equals("0")){
                            JOptionPane.showMessageDialog(this, "Đăng nhập thành công");                          
                            TrangChu nv = new TrangChu();
                            nv.setVisible(true);                           
                            dispose();
                        }else if(chucvu.equals("1")){                         
                            JOptionPane.showMessageDialog(this, "Đăng nhập thành công");                         
                             TrangChu admin = new TrangChu();                            
                            admin.setVisible(true);
                            dispose();
                        }
                    }
                   chucvu = rs.getString("ChucVu");
                }
                if(!flag){
                    JOptionPane.showMessageDialog(this, "Login failed");
                }
                rs.close();
                stmt.close();
                con.close();
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_dangnhapActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
         System.exit(0);
    }//GEN-LAST:event_btn_thoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangnhap;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
