/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRO1041.FORM;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import PRO1041.DAO.NhanVienDAO;
/**
/**
 *
 * @author phamt
 */
public class NhanVien extends javax.swing.JFrame {
    String username="sa";
    String password="123";
    String url="jdbc:sqlserver://localhost:1433;databaseName=QL_NhaXe";
    private String header[] = {"Mã NV","Họ Tên","Email","Số ĐT","Giới Tính","Chức Vụ","Hình Ảnh"};
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0);
    private ArrayList<NhanVienDAO> list = new ArrayList<NhanVienDAO>();
    
      
    String strHinhanh = null;
    String thongbao = "";
    private int curredIndex=-1;
    /**
     * Creates new form NhanVien
     */
    public NhanVien() {
        initComponents();         
        buttonGroup1.add(rb_nam);
        buttonGroup1.add(rb_nu);
        loadDataToTable();
        LoadData();
    }
    
     public void loadDataToTable(){
        try {
            tblModel.setRowCount(0);
            Connection con = DriverManager.getConnection(url,username,password);
            Statement st = con.createStatement();
            String sql = "select  * from NhanVien";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                Vector r = new Vector();
                r.add(rs.getInt(1));
                r.add(rs.getString(2));
                r.add(rs.getString(3));
                r.add(rs.getString(4));
                r.add(rs.getString(5));
                r.add(rs.getString(6));
                r.add(rs.getString(7));
              
                tblModel.addRow(r);
            }
            tbl_nv.setModel(tblModel);
            con.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    
     public void LoadData(){
         Connection conn = null;
         Statement stm = null;
        try {                      
            conn = DriverManager.getConnection(url,username,password);
            stm = conn.createStatement();
            String sql = "";
            sql = "select  * from NhanVien";
            ResultSet rs = stm.executeQuery(sql);
            list.clear();
            
            while(rs.next()){
            String MaNV = rs.getString("MaNV");         
            String TenNV = rs.getString("TenNV");
            String SDT = rs.getString("SoDT");
            boolean GioiTinh = rs.getBoolean("GioiTinh");
            String Email = rs.getString("Email");
            String ChucVu = rs.getString("ChucVu");
            String HinhAnh = rs.getString("Hinh");
            
            
            NhanVienDAO diemNV = new NhanVienDAO(MaNV, TenNV, SDT, GioiTinh, Email, ChucVu, HinhAnh);
            list.add(diemNV);
          }
            curredIndex=0;
            DislayNV();
            
            rs.close();
            stm.close();
            conn.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
    }
     
     public void LoadImage(String hinh){
        ImageIcon image1 = new ImageIcon("src\\IMG\\ImageNV\\" +hinh);
        Image im = image1.getImage();
        ImageIcon icon1 = new ImageIcon(im.getScaledInstance(btn_anh.getWidth(), btn_anh.getHeight(), im.SCALE_SMOOTH));
        btn_anh.setIcon(icon1);  
    }
      
       public void DislayNV(){
        NhanVienDAO nvs = list.get(curredIndex);
        txt_ma.setText(nvs.MaNV);
        txt_ten.setText(nvs.TenNV);
        txt_sdt.setText(nvs.SDT);     
        rb_nam.setSelected(nvs.GioiTinh);       
        rb_nu.setSelected(nvs.GioiTinh);
        txt_email.setText(nvs.Email);
        cbb_chucvu.setSelectedItem(nvs.ChucVu);
        LoadImage(nvs.HinhAnh);
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        txt_ma = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        rb_nam = new javax.swing.JRadioButton();
        rb_nu = new javax.swing.JRadioButton();
        cbb_chucvu = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_nv = new javax.swing.JTable();
        btn_anh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_timkiem = new javax.swing.JButton();
        txt_timkiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 90));

        jPanel1.setLayout(null);

        btn_them.setBackground(new java.awt.Color(162, 218, 246));
        btn_them.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/themnv.png"))); // NOI18N
        btn_them.setText("Thêm Nhân Viên");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel1.add(btn_them);
        btn_them.setBounds(100, 210, 440, 50);
        jPanel1.add(txt_ma);
        txt_ma.setBounds(150, 60, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 58, 145));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nhân Viên");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 10, 640, 44);

        jLabel8.setText("Tên nhân viên:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 110, 80, 14);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ảnh");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(600, 40, 80, 30);

        jLabel11.setText("Giới tính:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(70, 180, 60, 14);
        jPanel1.add(txt_ten);
        txt_ten.setBounds(150, 100, 180, 30);

        rb_nam.setText("Nam");
        jPanel1.add(rb_nam);
        rb_nam.setBounds(150, 180, 50, 23);

        rb_nu.setText("Nữ");
        jPanel1.add(rb_nu);
        rb_nu.setBounds(220, 180, 40, 23);

        cbb_chucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Nhân Viên", " " }));
        jPanel1.add(cbb_chucvu);
        cbb_chucvu.setBounds(410, 80, 90, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xoa.png"))); // NOI18N
        jButton1.setText("Xóa Nhân Viên");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 480, 170, 50);

        btn_sua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-bao-hanh.png"))); // NOI18N
        btn_sua.setText("Sửa Thông Tin");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sua);
        btn_sua.setBounds(390, 480, 170, 50);

        jLabel13.setText("Email:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(350, 120, 40, 14);

        jLabel12.setText("Chức vụ:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(350, 80, 50, 14);

        jLabel9.setText("SDT:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 150, 30, 14);
        jPanel1.add(txt_email);
        txt_email.setBounds(410, 120, 120, 30);
        jPanel1.add(txt_sdt);
        txt_sdt.setBounds(150, 140, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Mã nhân viên:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 70, 76, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Back");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 84, 40, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Reset");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 200, 40, 15);

        btn_back.setBackground(new java.awt.Color(244, 143, 143));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ql.png"))); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(10, 30, 50, 90);

        btn_reset.setBackground(new java.awt.Color(99, 114, 252));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset.png"))); // NOI18N
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset);
        btn_reset.setBounds(10, 140, 50, 90);

        tbl_nv.setBackground(new java.awt.Color(204, 204, 255));
        tbl_nv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_nv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_nvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_nv);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 340, 600, 90);

        btn_anh.setBackground(new java.awt.Color(169, 209, 238));
        btn_anh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btn_anh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anhActionPerformed(evt);
            }
        });
        jPanel1.add(btn_anh);
        btn_anh.setBounds(560, 70, 150, 160);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen2.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 10, 670, 250);

        btn_timkiem.setBackground(new java.awt.Color(204, 204, 0));
        btn_timkiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icontimnhanvien.png"))); // NOI18N
        btn_timkiem.setText("Tìm");
        btn_timkiem.setAlignmentY(0.0F);
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });
        jPanel1.add(btn_timkiem);
        btn_timkiem.setBounds(500, 280, 170, 49);

        txt_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemActionPerformed(evt);
            }
        });
        jPanel1.add(txt_timkiem);
        txt_timkiem.setBounds(70, 290, 400, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen3.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 0, 730, 550);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Untitled-3.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 0, 720, 450);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen1.png"))); // NOI18N
        background.setText("back");
        jPanel1.add(background);
        background.setBounds(0, 0, 770, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timkiemActionPerformed

    private void btn_anhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anhActionPerformed
        try {
               JFileChooser choose=new JFileChooser("src\\IMG\\ImageNV");
                 int chon=choose.showOpenDialog(this);
                 File file = choose.getSelectedFile();
                 Image img = ImageIO.read(file);
                 strHinhanh = file.getName();
                 int width = btn_anh.getWidth();
                 int height=   btn_anh.getHeight();
                 btn_anh.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));

        }catch(Exception e){
                System.out.println(e.toString());
        }
    }//GEN-LAST:event_btn_anhActionPerformed

    private void tbl_nvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_nvMouseClicked
        int r = tbl_nv.getSelectedRow();
        if (r < 0) {
            return;
        }
            txt_ma.setText(tbl_nv.getValueAt(r, 0).toString());
            txt_ten.setText(tbl_nv.getValueAt(r, 1).toString());
            txt_sdt.setText(tbl_nv.getValueAt(r, 2).toString());
            txt_email.setText(tbl_nv.getValueAt(r, 3).toString());
        if ((tbl_nv.getValueAt(r, 4).toString()).equals("1")) {
            rb_nam.setSelected(true);
        }else {
            rb_nu.setSelected(true);
        }
            cbb_chucvu.setSelectedItem(tbl_nv.getValueAt(r, 5).toString());
            LoadImage(tbl_nv.getValueAt(r, 6).toString());
    }//GEN-LAST:event_tbl_nvMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, username, password);
            String sql = "insert into NhanVien values(?,?,?,?,?,?)\n";
            PreparedStatement st = con.prepareStatement(sql);
                st.setString(1, txt_ten.getText());
                st.setString(2, txt_sdt.getText());
                st.setString(3, txt_email.getText());
                st.setString(5, cbb_chucvu.getSelectedItem().toString());
                st.setString(6, strHinhanh);
                boolean gt;
                if (rb_nam.isSelected()) {
                    gt = true;
                } else {
                    gt = false;
                }
                st.setBoolean(4, gt);

            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công");
            con.close();
            loadDataToTable();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        int i;
        String manv = txt_timkiem.getText();
        for (i = 0; i < list.size(); i++) {
            NhanVienDAO nv = list.get(i);
            if (nv.MaNV.equals(manv) == true) {                
                curredIndex = i;
                tbl_nv.setRowSelectionInterval(curredIndex, curredIndex);      
                DislayNV();
                break;
            }
        }
        if (i == list.size()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên");
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Có",
                JOptionPane.YES_NO_OPTION);
        if (ret != JOptionPane.YES_OPTION) {
            return;
        }
        Connection c = null;
        PreparedStatement ps = null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            c = DriverManager.getConnection(url, username, password);
            ps = c.prepareStatement("Delete From NhanVien where MaNV = ?");
            ps.setString(1, txt_ma.getText());
            String ten = txt_ten.getText();
            ret = ps.executeUpdate();
            if (ret != -1) {
                JOptionPane.showMessageDialog(this, "Đã xóa nhân viên " + ten);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (c != null) {
                    c.close();
                }
                if (ps != null) {
                    ps.close();
                    loadDataToTable();
                    LoadData();
                }
            } catch (Exception ex2) {
                ex2.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, username, password);
            String sql = "update NhanVien set TenNV=?, SoDT=?, Email=?, GioiTinh=?, ChucVu=?, Hinh=? where MaNV=?";
            PreparedStatement st = con.prepareStatement(sql);
                st.setString(1, txt_ten.getText());
                st.setString(2, txt_sdt.getText());
                st.setString(3, txt_email.getText());
                st.setString(6, strHinhanh);
                boolean gt;
                if (rb_nam.isSelected()) {
                    gt = true;
                } else {
                    gt = false;
                }
                st.setBoolean(4, gt);
                st.setString(5, cbb_chucvu.getSelectedItem().toString());
                st.setString(7, txt_ma.getText());
                st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Sửa thông tin thành công thành công");
            con.close();
            loadDataToTable();
            LoadData();

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        TrangChu tx = new TrangChu();
        tx.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        txt_ma.setText("");
        txt_ten.setText("");
        txt_sdt.setText("");     
        rb_nam.setSelected(false);       
        rb_nu.setSelected(false);
        txt_email.setText("");
        cbb_chucvu.setSelectedItem("");
        LoadImage("");
        
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_anh;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbb_chucvu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_nam;
    private javax.swing.JRadioButton rb_nu;
    private javax.swing.JTable tbl_nv;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
