/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRO1041.FORM;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import PRO1041.DAO.TaiXeDAO;

/**
 *
 * @author phamt
 */
public class TaiXe extends javax.swing.JFrame {
    String username = "sa";
    String password = "123";
    String url = "jdbc:sqlserver://localhost:1433;databaseName=QL_NhaXe";
    private String header[] = {"Mã Tài Xế", "Họ Tên", "Số DT", "Giới Tính", "Hinh","Mã Xe"};
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0);
    private ArrayList<TaiXeDAO> list = new ArrayList<TaiXeDAO>();

    String strHinhanh = null;
    String thongbao = "";
    private int curredIndex = -1;
    /**
     * Creates new form NhanVien
     */
    public TaiXe() {
        initComponents();        
        buttonGroup1.add(rb_nam);
        buttonGroup1.add(rb_nu);
        loadDataToTable();
        LoadData();
    }
    
    public void loadDataToTable() {
        try {
            tblModel.setRowCount(0);
            Connection con = DriverManager.getConnection(url, username, password);
            Statement st = con.createStatement();
            String sql = "select  * from TaiXe";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Vector r = new Vector();
                r.add(rs.getInt(1));
                r.add(rs.getString(2));
                r.add(rs.getString(3));
                r.add(rs.getString(4));
                r.add(rs.getString(5));
                r.add(rs.getString(6));

                tblModel.addRow(r);
            }
            tbl_tx.setModel(tblModel);
            con.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    public void LoadData() {
        Connection conn = null;
        Statement stm = null;
        try {
            conn = DriverManager.getConnection(url, username, password);
            stm = conn.createStatement();
            String sql = "";
            sql = "select  * from TaiXe";
            ResultSet rs = stm.executeQuery(sql);
            list.clear();

            while (rs.next()) {
                String MaTX = rs.getString("MaTX");
                String TenTX = rs.getString("TenTX");
                String SDT = rs.getString("SDT");
                boolean GioiTinh = rs.getBoolean("GioiTinh");
                String HinhAnh = rs.getString("HinhAnh");
                String MaXe = rs.getString("MaXe");

                TaiXeDAO diemsv = new TaiXeDAO(MaTX, TenTX, SDT, GioiTinh, HinhAnh, MaXe);
                list.add(diemsv);
            }
            curredIndex = 0;
            DislayTX();

            rs.close();
            stm.close();
            conn.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }

    public void LoadImage(String hinh) {
        ImageIcon image = new ImageIcon("src\\IMG\\ImageTX\\" + hinh);
        Image im = image.getImage();
        ImageIcon icon = new ImageIcon(im.getScaledInstance(btn_anh.getWidth(), btn_anh.getHeight(), im.SCALE_SMOOTH));
        btn_anh.setIcon(icon);
    }

    public void DislayTX() {
        TaiXeDAO txs = list.get(curredIndex);
        txt_ma.setText(txs.MaTX);
        txt_ten.setText(txs.TenTX);
        txt_sdt.setText(txs.SDT + "");
        rb_nam.setSelected(txs.GioiTinh);
        rb_nu.setSelected(txs.GioiTinh);
        cbb_maxe.setSelectedItem(txs.MaXe);
        LoadImage(txs.HinhAnh);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        txt_ma = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rb_nam = new javax.swing.JRadioButton();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        rb_nu = new javax.swing.JRadioButton();
        cbb_maxe = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tx = new javax.swing.JTable();
        btn_anh = new javax.swing.JButton();
        btn_timkiem = new javax.swing.JButton();
        txt_timkiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 90));

        jPanel1.setLayout(null);

        btn_them.setBackground(new java.awt.Color(162, 218, 246));
        btn_them.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/themnv.png"))); // NOI18N
        btn_them.setText("Thêm Tài Xế");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel1.add(btn_them);
        btn_them.setBounds(100, 210, 440, 50);
        jPanel1.add(txt_ma);
        txt_ma.setBounds(150, 70, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 58, 145));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tài Xế");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 20, 640, 44);

        jLabel8.setText("Số điện thoại:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 160, 70, 14);
        jPanel1.add(txt_sdt);
        txt_sdt.setBounds(150, 150, 180, 30);

        jLabel9.setText("Giới tính:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(360, 80, 60, 14);

        jLabel12.setText("Tên tài xế: ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 120, 60, 20);
        jPanel1.add(txt_ten);
        txt_ten.setBounds(150, 110, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Mã tài xế:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 80, 60, 15);

        rb_nam.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rb_nam);
        rb_nam.setText("Nam");
        jPanel1.add(rb_nam);
        rb_nam.setBounds(360, 100, 60, 23);

        btn_xoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xoa.png"))); // NOI18N
        btn_xoa.setText("Xóa ");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_xoa);
        btn_xoa.setBounds(220, 480, 180, 60);

        btn_sua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-bao-hanh.png"))); // NOI18N
        btn_sua.setText("Sửa Thông Tin");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sua);
        btn_sua.setBounds(470, 480, 180, 60);

        rb_nu.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rb_nu);
        rb_nu.setText("Nữ");
        jPanel1.add(rb_nu);
        rb_nu.setBounds(440, 100, 60, 23);

        cbb_maxe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", " " }));
        jPanel1.add(cbb_maxe);
        cbb_maxe.setBounds(430, 150, 60, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Ảnh");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(590, 40, 60, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Mã xe:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 150, 70, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Back");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 84, 40, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Reset");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 200, 40, 15);

        btn_back.setBackground(new java.awt.Color(244, 143, 143));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ql.png"))); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(10, 30, 50, 90);

        btn_reset.setBackground(new java.awt.Color(99, 114, 252));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset.png"))); // NOI18N
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset);
        btn_reset.setBounds(10, 140, 50, 90);

        tbl_tx.setBackground(new java.awt.Color(204, 204, 255));
        tbl_tx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_tx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_txMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_tx);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 350, 660, 110);

        btn_anh.setBackground(new java.awt.Color(169, 209, 238));
        btn_anh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btn_anh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anhActionPerformed(evt);
            }
        });
        jPanel1.add(btn_anh);
        btn_anh.setBounds(550, 70, 200, 150);

        btn_timkiem.setBackground(new java.awt.Color(204, 204, 0));
        btn_timkiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icontimnhanvien.png"))); // NOI18N
        btn_timkiem.setText("Tìm");
        btn_timkiem.setAlignmentY(0.0F);
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });
        jPanel1.add(btn_timkiem);
        btn_timkiem.setBounds(500, 280, 170, 49);

        txt_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemActionPerformed(evt);
            }
        });
        jPanel1.add(txt_timkiem);
        txt_timkiem.setBounds(90, 290, 400, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen3.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 20, 790, 530);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/brtaixe.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(124, 14, 660, 430);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen2.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 10, 720, 460);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen1.png"))); // NOI18N
        background.setText("back");
        jPanel1.add(background);
        background.setBounds(0, 0, 830, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timkiemActionPerformed

    private void btn_anhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anhActionPerformed
          try {
               JFileChooser choose=new JFileChooser("src\\IMG\\ImageTX");
                 int chon=choose.showOpenDialog(this);
                 File file = choose.getSelectedFile();
                 Image img = ImageIO.read(file);
                 strHinhanh = file.getName();
                 int width = btn_anh.getWidth();
                 int height= btn_anh.getHeight();
                 btn_anh.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
            }catch(Exception e){            
            }
    }//GEN-LAST:event_btn_anhActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, username, password);
            String sql = "insert into TaiXe values(?,?,?,?,?)\n";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, txt_ten.getText());
            st.setString(2, txt_sdt.getText());
            st.setString(4, strHinhanh);
            st.setString(5, cbb_maxe.getSelectedItem().toString());
            boolean gt;
            if (rb_nam.isSelected()) {
                gt = true;
            } else {
                gt = false;
            }
            st.setBoolean(3, gt);

            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Thêm tài xế thành công");
            con.close();
            loadDataToTable();
        } catch (Exception e) {

            System.out.println(e);

        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        int i;
        String matx = txt_timkiem.getText();
        for (i = 0; i < list.size(); i++) {
            TaiXeDAO tx = list.get(i);
            if (tx.MaTX.equals(matx) == true) {
                curredIndex = i;
                tbl_tx.setRowSelectionInterval(curredIndex, curredIndex);      
                DislayTX();
                break;
            }
        }
        if (i == list.size()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy tài xế");
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Có",
                JOptionPane.YES_NO_OPTION);
        if (ret != JOptionPane.YES_OPTION) {
            return;
        }
        Connection c = null;
        PreparedStatement ps = null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            c = DriverManager.getConnection(url, username, password);
            ps = c.prepareStatement("Delete From TaiXe where MaTX = ?");
            ps.setString(1, txt_ma.getText());
            String ten = txt_ten.getText();
            ret = ps.executeUpdate();
            if (ret != -1) {
                JOptionPane.showMessageDialog(this, "Đã xóa tài xế " + ten);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (c != null) {
                    c.close();
                }
                if (ps != null) {
                    ps.close();
                    loadDataToTable();
                    LoadData();
                }
            } catch (Exception ex2) {
                ex2.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, username, password);
            String sql = "update TaiXe set TenTX=?, SDT=?, GioiTinh=?,  HinhAnh=?, MaXe=? where MaTX=?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, txt_ten.getText());
            st.setString(2, txt_sdt.getText());
            st.setString(4, strHinhanh);
            st.setString(5, cbb_maxe.getSelectedItem().toString());
            boolean gt;
            if (rb_nam.isSelected()) {
                gt = true;
            } else {
                gt = false;
            }
            st.setBoolean(3, gt);
            st.setString(6, txt_ma.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Sửa thông tin tài xế thành công");
            con.close();
            loadDataToTable();
            LoadData();

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
            TrangChu tc = new TrangChu();
            tc.setVisible(true);
            dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        txt_ma.setText("");
        txt_ten.setText("");
        txt_sdt.setText("");
        rb_nam.setSelected(false);
        rb_nu.setSelected(false);
        cbb_maxe.setSelectedItem("");
        LoadImage("");
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tbl_txMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_txMouseClicked
       int r = tbl_tx.getSelectedRow();
        if (r < 0) {
            return;
        }
        txt_ma.setText(tbl_tx.getValueAt(r, 0).toString());
        txt_ten.setText(tbl_tx.getValueAt(r, 1).toString());
        txt_sdt.setText(tbl_tx.getValueAt(r, 2).toString());
        if ((tbl_tx.getValueAt(r, 3).toString()).equals("1")) {
            rb_nam.setSelected(true);
        } else {
            rb_nu.setSelected(true);
        }
        cbb_maxe.setSelectedItem(tbl_tx.getValueAt(r, 5).toString());
        LoadImage(tbl_tx.getValueAt(r, 4).toString());
    }//GEN-LAST:event_tbl_txMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaiXe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_anh;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbb_maxe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_nam;
    private javax.swing.JRadioButton rb_nu;
    private javax.swing.JTable tbl_tx;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
