/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRO1041.FORM;

import java.awt.Color;

/**
 *
 * @author phamt
 */
public class TrangChu extends javax.swing.JFrame {
    DangNhap dn= new DangNhap();
    
    /**
     * Creates new form NewJFrame
     */
    public TrangChu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        BXMDHUE1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        THOIGIANDI1 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        toolBar1 = new javax.swing.JToolBar();
        btn_datve = new javax.swing.JButton();
        btn_taixe = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_nhanvien = new javax.swing.JButton();
        btn_tuyen = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btn_dangxuat = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        BANGGIAVE = new javax.swing.JLabel();
        BXMDHUE = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        THOIGIANDI = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NEN2 = new javax.swing.JLabel();
        ANHBACKGROUND = new javax.swing.JLabel();
        BACKGROUND = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nhanvien = new javax.swing.JMenuItem();
        taixe = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        tuyenduong = new javax.swing.JMenuItem();
        xe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 150));
        setMinimumSize(new java.awt.Dimension(636, 462));

        jPanel1.setLayout(null);

        jPanel14.setBackground(new java.awt.Color(153, 153, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(204, 0, 0));
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("Vip :");
        jPanel14.add(jLabel68);

        jLabel69.setText("450.000đ");
        jPanel14.add(jLabel69);

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(204, 0, 0));
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("Thường :");
        jPanel14.add(jLabel70);

        jLabel71.setText("350.000đ");
        jPanel14.add(jLabel71);

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(204, 0, 0));
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("Ghế ngồi :");
        jPanel14.add(jLabel72);

        jLabel73.setText("200.000đ");
        jPanel14.add(jLabel73);

        jPanel1.add(jPanel14);
        jPanel14.setBounds(130, 290, 550, 40);

        BXMDHUE1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BXMDHUE1.setForeground(new java.awt.Color(0, 0, 255));
        BXMDHUE1.setText("Bến Xe Miền Đông                         Huế");
        jPanel1.add(BXMDHUE1);
        BXMDHUE1.setBounds(130, 250, 480, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xechay.gif"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(300, 260, 170, 30);

        THOIGIANDI1.setForeground(new java.awt.Color(255, 0, 0));
        THOIGIANDI1.setText("Thời gian đi từ 8 đến 12 tiếng");
        jPanel1.add(THOIGIANDI1);
        THOIGIANDI1.setBounds(320, 330, 250, 20);

        jButton18.setBackground(new java.awt.Color(255, 255, 51));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(51, 0, 51));
        jButton18.setText("Đặt nhanh");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(220, 350, 400, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen3.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 240, 550, 160);

        toolBar1.setBackground(new java.awt.Color(204, 51, 255));
        toolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null));
        toolBar1.setFloatable(false);
        toolBar1.setForeground(new java.awt.Color(240, 240, 240));
        toolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        toolBar1.setRollover(true);
        toolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        toolBar1.setName(""); // NOI18N

        btn_datve.setBackground(new java.awt.Color(255, 255, 255));
        btn_datve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/datve.png"))); // NOI18N
        btn_datve.setText("Đặt Vé");
        btn_datve.setAlignmentX(0.5F);
        btn_datve.setFocusable(false);
        btn_datve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_datve.setMargin(new java.awt.Insets(5, 30, 5, 30));
        btn_datve.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_datve.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_datve.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn_datveMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_datveMouseMoved(evt);
            }
        });
        btn_datve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datveActionPerformed(evt);
            }
        });
        toolBar1.add(btn_datve);

        btn_taixe.setBackground(new java.awt.Color(255, 255, 255));
        btn_taixe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/taixe.png"))); // NOI18N
        btn_taixe.setText("Tài Xế");
        btn_taixe.setAlignmentX(0.5F);
        btn_taixe.setFocusable(false);
        btn_taixe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_taixe.setMargin(new java.awt.Insets(5, 30, 5, 30));
        btn_taixe.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_taixe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_taixe.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_taixeMouseMoved(evt);
            }
        });
        btn_taixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taixeActionPerformed(evt);
            }
        });
        toolBar1.add(btn_taixe);

        jSeparator2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator2.setForeground(new java.awt.Color(255, 0, 0));
        toolBar1.add(jSeparator2);

        btn_nhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nhanvien.png"))); // NOI18N
        btn_nhanvien.setText("Nhân Viên");
        btn_nhanvien.setAlignmentX(0.5F);
        btn_nhanvien.setFocusable(false);
        btn_nhanvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nhanvien.setMargin(new java.awt.Insets(5, 20, 5, 20));
        btn_nhanvien.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_nhanvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nhanvien.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_nhanvienMouseMoved(evt);
            }
        });
        btn_nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhanvienActionPerformed(evt);
            }
        });
        toolBar1.add(btn_nhanvien);

        btn_tuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tuyenduong.png"))); // NOI18N
        btn_tuyen.setText("Tuyến");
        btn_tuyen.setAlignmentX(0.5F);
        btn_tuyen.setFocusable(false);
        btn_tuyen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_tuyen.setMargin(new java.awt.Insets(5, 20, 5, 20));
        btn_tuyen.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_tuyen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_tuyen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_tuyenMouseMoved(evt);
            }
        });
        btn_tuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tuyenActionPerformed(evt);
            }
        });
        toolBar1.add(btn_tuyen);
        toolBar1.add(jSeparator3);

        btn_dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dangxuat.png"))); // NOI18N
        btn_dangxuat.setText("Đăng Xuất");
        btn_dangxuat.setAlignmentX(0.5F);
        btn_dangxuat.setFocusable(false);
        btn_dangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dangxuat.setMargin(new java.awt.Insets(5, 20, 5, 20));
        btn_dangxuat.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_dangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangxuatActionPerformed(evt);
            }
        });
        toolBar1.add(btn_dangxuat);

        btn_thoat.setBackground(new java.awt.Color(255, 255, 255));
        btn_thoat.setForeground(new java.awt.Color(255, 0, 0));
        btn_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        btn_thoat.setText("Thoát");
        btn_thoat.setAlignmentX(0.5F);
        btn_thoat.setFocusable(false);
        btn_thoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_thoat.setMargin(new java.awt.Insets(5, 30, 5, 30));
        btn_thoat.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_thoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        toolBar1.add(btn_thoat);

        jPanel1.add(toolBar1);
        toolBar1.setBounds(0, 0, 110, 550);

        BANGGIAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/bangiave.png"))); // NOI18N
        jPanel1.add(BANGGIAVE);
        BANGGIAVE.setBounds(190, 0, 330, 90);

        BXMDHUE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BXMDHUE.setForeground(new java.awt.Color(0, 0, 255));
        BXMDHUE.setText("Bến Xe Miền Đông                         Huế");
        jPanel1.add(BXMDHUE);
        BXMDHUE.setBounds(130, 80, 480, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xechay.gif"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 90, 170, 30);

        jPanel13.setBackground(new java.awt.Color(153, 153, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(204, 0, 0));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("Vip :");
        jPanel13.add(jLabel62);

        jLabel63.setText("450.000đ");
        jPanel13.add(jLabel63);

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(204, 0, 0));
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("Thường :");
        jPanel13.add(jLabel64);

        jLabel65.setText("350.000đ");
        jPanel13.add(jLabel65);

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(204, 0, 0));
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Ghế ngồi :");
        jPanel13.add(jLabel66);

        jLabel67.setText("200.000đ");
        jPanel13.add(jLabel67);

        jPanel1.add(jPanel13);
        jPanel13.setBounds(130, 120, 550, 40);

        THOIGIANDI.setForeground(new java.awt.Color(255, 0, 0));
        THOIGIANDI.setText("Thời gian đi từ 8 đến 12 tiếng");
        jPanel1.add(THOIGIANDI);
        THOIGIANDI.setBounds(320, 160, 250, 20);

        jButton17.setBackground(new java.awt.Color(255, 255, 51));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(51, 0, 51));
        jButton17.setText("Đặt nhanh");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(220, 180, 400, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen3.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 70, 550, 160);

        NEN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen2.png"))); // NOI18N
        jPanel1.add(NEN2);
        NEN2.setBounds(130, 70, 550, 450);

        ANHBACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/xekhach.png"))); // NOI18N
        jPanel1.add(ANHBACKGROUND);
        ANHBACKGROUND.setBounds(10, -10, 690, 510);

        BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen1.png"))); // NOI18N
        jPanel1.add(BACKGROUND);
        BACKGROUND.setBounds(0, 0, 700, 550);

        jMenu1.setText("Quản lý nhân sự");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        nhanvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        nhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nhanvien.png"))); // NOI18N
        nhanvien.setText("Nhân Viên");
        nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanvienActionPerformed(evt);
            }
        });
        jMenu1.add(nhanvien);

        taixe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        taixe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/taixe.png"))); // NOI18N
        taixe.setText("Tài Xế");
        taixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taixeActionPerformed(evt);
            }
        });
        jMenu1.add(taixe);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý hoạt động");

        tuyenduong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_MASK));
        tuyenduong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tuyenduong.png"))); // NOI18N
        tuyenduong.setText("Tuyến Đường");
        tuyenduong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuyenduongActionPerformed(evt);
            }
        });
        jMenu2.add(tuyenduong);

        xe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        xe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xechay.gif"))); // NOI18N
        xe.setText("Xe");
        xe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xeActionPerformed(evt);
            }
        });
        jMenu2.add(xe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_taixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taixeActionPerformed
        TaiXe tx = new TaiXe();
        tx.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_taixeActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void btn_nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhanvienActionPerformed
        NhanVien nv = new NhanVien();
        nv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_nhanvienActionPerformed

    private void btn_tuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tuyenActionPerformed
      TuyenDuong td = new TuyenDuong();
      td.setVisible(true);
      dispose();
    }//GEN-LAST:event_btn_tuyenActionPerformed

    private void btn_datveMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datveMouseMoved
        btn_datve.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_btn_datveMouseMoved

    private void btn_datveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datveMouseDragged
        
    }//GEN-LAST:event_btn_datveMouseDragged

    private void btn_taixeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_taixeMouseMoved
        btn_taixe.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_taixeMouseMoved

    private void btn_nhanvienMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nhanvienMouseMoved
       btn_nhanvien.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_nhanvienMouseMoved

    private void btn_tuyenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tuyenMouseMoved
        btn_tuyen.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_tuyenMouseMoved

    private void btn_datveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datveActionPerformed
        DatVe dv = new DatVe();
        dv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_datveActionPerformed

    private void btn_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangxuatActionPerformed
      DangNhap dn = new DangNhap();
      dn.setVisible(true);
      dispose();
    }//GEN-LAST:event_btn_dangxuatActionPerformed

    private void tuyenduongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuyenduongActionPerformed
      TuyenDuong td = new TuyenDuong();
      td.setVisible(true);
      dispose();
    }//GEN-LAST:event_tuyenduongActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        DatVe dv = new DatVe();
        dv.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        DatVe dv = new DatVe();
        dv.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanvienActionPerformed
        NhanVien nv = new NhanVien();
        nv.setVisible(true);
        dispose();
    }//GEN-LAST:event_nhanvienActionPerformed

    private void taixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taixeActionPerformed
        TaiXe tx = new TaiXe();
        tx.setVisible(true);
        dispose();
    }//GEN-LAST:event_taixeActionPerformed

    private void xeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xeActionPerformed
        Xe xe = new Xe();
        xe.setVisible(true);
        dispose();
    }//GEN-LAST:event_xeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ANHBACKGROUND;
    private javax.swing.JLabel BACKGROUND;
    private javax.swing.JLabel BANGGIAVE;
    private javax.swing.JLabel BXMDHUE;
    private javax.swing.JLabel BXMDHUE1;
    private javax.swing.JLabel NEN2;
    private javax.swing.JLabel THOIGIANDI;
    private javax.swing.JLabel THOIGIANDI1;
    private javax.swing.JButton btn_dangxuat;
    private javax.swing.JButton btn_datve;
    private javax.swing.JButton btn_nhanvien;
    private javax.swing.JButton btn_taixe;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_tuyen;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JMenuItem nhanvien;
    private javax.swing.JMenuItem taixe;
    private javax.swing.JToolBar toolBar1;
    private javax.swing.JMenuItem tuyenduong;
    private javax.swing.JMenuItem xe;
    // End of variables declaration//GEN-END:variables
}
