/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRO1041.FORM;

import PRO1041.DAO.KhachHangDAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import PRO1041.DAO.TuyenDuongDAO;
/**
 *
 * @author phamt
 */
public class TuyenDuong extends javax.swing.JFrame {
    String username = "sa";
    String password = "123";
    String url = "jdbc:sqlserver://localhost:1433;databaseName=QL_NhaXe";
    private String header[] = {"Mã Tuyến", "Tên Tuyến", "Điểm Đi", "Điểm Đến"};
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0);
    private ArrayList<TuyenDuongDAO> list = new ArrayList<TuyenDuongDAO>();

    String strHinhanh = null;
    String thongbao = "";
    private int curredIndex = -1;
    /**
     * Creates new form TuyenDuong
     */
    public TuyenDuong() {
        initComponents();
        loadDataToTable();
        LoadData();
    }
    
    public void loadDataToTable() {
        try {
            tblModel.setRowCount(0);
            Connection con = DriverManager.getConnection(url, username, password);
            Statement st = con.createStatement();
            String sql = "select  * from TuyenDuong";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Vector r = new Vector();
                r.add(rs.getInt(1));
                r.add(rs.getString(2));
                r.add(rs.getString(3));
                r.add(rs.getString(4));
                

                tblModel.addRow(r);
            }
            tbl_td.setModel(tblModel);
            con.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    
    public void LoadData(){
         Connection conn = null;
         Statement stm = null;
        try {                      
            conn = DriverManager.getConnection(url, username, password);
            stm = conn.createStatement();
            String sql = "";
            sql = "select  * from TuyenDuong";
            ResultSet rs = stm.executeQuery(sql);
            list.clear();
            
            while(rs.next()){
            String MaTuyen = rs.getString("MaChuyen");         
            String TenTuyen = rs.getString("TenChuyen");
            String DiemDi = rs.getString("DiemDi");
            String DiemDen = rs.getString("DiemDen");          
            TuyenDuongDAO tdd= new TuyenDuongDAO(MaTuyen, TenTuyen, DiemDi, DiemDen);
            list.add(tdd);
          }
            curredIndex=0;
            DislayNV();
            
            rs.close();
            stm.close();
            conn.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
    }
      
         public void DislayNV(){
        TuyenDuongDAO tds = list.get(curredIndex);
        txt_ma.setText(tds.MaTuyen);
        txt_ten.setText(tds.TenTuyen);
        txt_diemdi.setText(tds.DiemDi);
        txt_diemden.setText(tds.DiemDen);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_tim = new javax.swing.JButton();
        txt_tim = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_td = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        txt_diemdi = new javax.swing.JTextField();
        txt_diemden = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 90));

        jPanel1.setLayout(null);

        btn_tim.setBackground(new java.awt.Color(204, 204, 0));
        btn_tim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Untitled-1.png"))); // NOI18N
        btn_tim.setText("Tìm");
        btn_tim.setAlignmentY(0.0F);
        btn_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tim);
        btn_tim.setBounds(500, 310, 170, 50);

        txt_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timActionPerformed(evt);
            }
        });
        jPanel1.add(txt_tim);
        txt_tim.setBounds(70, 320, 400, 30);

        tbl_td.setBackground(new java.awt.Color(204, 204, 255));
        tbl_td.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_td.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_td);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 370, 670, 90);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Điểm đi:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(120, 180, 60, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Back");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 140, 50, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/xechay - Copy.gif"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(250, 170, 80, 30);

        btn_them.setBackground(new java.awt.Color(204, 204, 255));
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btn_them.setText("Thêm");
        jPanel1.add(btn_them);
        btn_them.setBounds(210, 250, 350, 40);
        jPanel1.add(txt_diemdi);
        txt_diemdi.setBounds(210, 200, 150, 30);
        jPanel1.add(txt_diemden);
        txt_diemden.setBounds(430, 200, 160, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Điểm đến:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(370, 170, 70, 30);

        btn_xoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xoa.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_xoa);
        btn_xoa.setBounds(170, 470, 170, 50);

        btn_sua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-bao-hanh.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sua);
        btn_sua.setBounds(410, 470, 170, 50);

        btn_back.setBackground(new java.awt.Color(244, 143, 143));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset.png"))); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(20, 30, 70, 190);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Reset");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(670, 150, 70, 20);

        btn_reset.setBackground(new java.awt.Color(99, 114, 252));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset.png"))); // NOI18N
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset);
        btn_reset.setBounds(650, 40, 70, 190);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tên tuyến đường:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 130, 120, 30);
        jPanel1.add(txt_ten);
        txt_ten.setBounds(250, 130, 340, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Mã tuyến đường:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(110, 90, 110, 30);
        jPanel1.add(txt_ma);
        txt_ma.setBounds(250, 90, 340, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tuyến Đường");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 30, 640, 44);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen2.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 30, 710, 280);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen3.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, -20, 720, 580);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/xekhach.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 0, 750, 540);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timActionPerformed

    private void tbl_tdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tdMouseClicked
        int r = tbl_td.getSelectedRow();
        if (r < 0) {
            return;
        }
        txt_ma.setText(tbl_td.getValueAt(r, 0).toString());
        txt_ten.setText(tbl_td.getValueAt(r, 1).toString());           
        txt_diemdi.setText(tbl_td.getValueAt(r, 2).toString());
        txt_diemden.setText(tbl_td.getValueAt(r, 3).toString());
     
    }//GEN-LAST:event_tbl_tdMouseClicked

    private void btn_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timActionPerformed
        int i;
        String makh = txt_tim.getText();
        for (i = 0; i < list.size(); i++) {
            TuyenDuongDAO td = list.get(i);
            if (td.MaTuyen.equals(makh) == true) {
                curredIndex = i;
            tbl_td.setRowSelectionInterval(curredIndex, curredIndex);              
                DislayNV();
                break;
            }
        }
        if (i == list.size()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy tuyến");
        }
    }//GEN-LAST:event_btn_timActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
         txt_ma.setText("");
        txt_ten.setText("");
        txt_diemdi.setText("");
        txt_diemden.setText("");
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
         int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Có",
                JOptionPane.YES_NO_OPTION);
        if (ret != JOptionPane.YES_OPTION) {
            return;
        }
        Connection c = null;
        PreparedStatement ps = null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            c = DriverManager.getConnection(url, username, password);
            ps = c.prepareStatement("Delete From TuyenDuong where MaChuyen = ?");
            ps.setString(1, txt_ma.getText());
            String ten = txt_ten.getText();
            ret = ps.executeUpdate();
            if (ret != -1) {
                JOptionPane.showMessageDialog(this, "Đã xóa tuyến đường " + ten);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (c != null) {
                    c.close();
                }
                if (ps != null) {
                    ps.close();
                    loadDataToTable();
                    LoadData();
                }
            } catch (Exception ex2) {
                ex2.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, username, password);
            String sql = "update TuyenDuong set TenChuyen=?, DiemDi=?, DiemDen=? where MaChuyen=?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, txt_ten.getText());
            st.setString(2, txt_diemdi.getText());   
            st.setString(3, txt_diemden.getText());
            st.setString(4, txt_ma.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Sửa thông tin tuyến đường thành công");
            con.close();
            loadDataToTable();
            LoadData();

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
            TrangChu tc = new TrangChu();
            tc.setVisible(true);
            dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TuyenDuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TuyenDuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TuyenDuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TuyenDuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TuyenDuong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_tim;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_td;
    private javax.swing.JTextField txt_diemden;
    private javax.swing.JTextField txt_diemdi;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_tim;
    // End of variables declaration//GEN-END:variables
}
