/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRO1041.FORM;


import PRO1041.DAO.TaiXeDAO;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import PRO1041.DAO.XeDAO;
/**
 *
 * @author phamt
 */
public class Xe extends javax.swing.JFrame {
    String username = "sa";
    String password = "123";
    String url = "jdbc:sqlserver://localhost:1433;databaseName=QL_NhaXe";
    private String header[] = {"Mã Xe", "Biển Số", "Trạng Thái", "Hình Ảnh"};
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0);
    private ArrayList<XeDAO> list = new ArrayList<XeDAO>();

    String strHinhanh = null;
    String thongbao = "";
    private int curredIndex = -1;
    /**
     * Creates new form TuyenDuong
     */
    public Xe() {
        initComponents();
        loadDataToTable();
        LoadData();
    }
    
    public void loadDataToTable() {
        try {
            tblModel.setRowCount(0);
            Connection con = DriverManager.getConnection(url, username, password);
            Statement st = con.createStatement();
            String sql = "select  * from Xe";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Vector r = new Vector();
                r.add(rs.getInt(1));
                r.add(rs.getString(2));
                r.add(rs.getString(3));
                r.add(rs.getString(4));
             

                tblModel.addRow(r);
            }
            tbl_xe.setModel(tblModel);
            con.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    public void LoadData() {
        Connection conn = null;
        Statement stm = null;
        try {
            conn = DriverManager.getConnection(url, username, password);
            stm = conn.createStatement();
            String sql = "";
            sql = "select  * from Xe";
            ResultSet rs = stm.executeQuery(sql);
            list.clear();

            while (rs.next()) {
                String MaXe = rs.getString("MaXe");
                String BienSo = rs.getString("BienSo");
                String TrangThai = rs.getString("TrangThai");             
                String HinhAnh = rs.getString("HinhAnh");          
                XeDAO xe = new XeDAO(MaXe, BienSo, TrangThai, HinhAnh);              
                list.add(xe);
            }
            curredIndex = 0;
            DislayTX();

            rs.close();
            stm.close();
            conn.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }

    public void LoadImage(String hinh) {
        ImageIcon image = new ImageIcon("src\\IMG\\ImageXe\\" + hinh);
        Image im = image.getImage();
        ImageIcon icon = new ImageIcon(im.getScaledInstance(btn_anh.getWidth(), btn_anh.getHeight(), im.SCALE_SMOOTH));
        btn_anh.setIcon(icon);
    }

    public void DislayTX() {
        XeDAO txs = list.get(curredIndex);
        txt_ma.setText(txs.MaXe);
        txt_bienso.setText(txs.BienSo);
        cbb_trangthai.setSelectedItem(txs.TrangThai);
        LoadImage(txs.HinhAnh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_tim = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_xe = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_anh = new javax.swing.JButton();
        btn_tim = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbb_trangthai = new javax.swing.JComboBox<>();
        btn_sua = new javax.swing.JButton();
        txt_bienso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 90));

        jPanel1.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Trạng thái");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(110, 170, 80, 17);

        txt_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timActionPerformed(evt);
            }
        });
        jPanel1.add(txt_tim);
        txt_tim.setBounds(70, 320, 400, 30);

        tbl_xe.setBackground(new java.awt.Color(204, 204, 255));
        tbl_xe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_xe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_xeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_xe);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 360, 670, 90);

        btn_them.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btn_them.setText("THÊM");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel1.add(btn_them);
        btn_them.setBounds(200, 250, 300, 40);

        btn_anh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btn_anh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anhActionPerformed(evt);
            }
        });
        jPanel1.add(btn_anh);
        btn_anh.setBounds(520, 70, 190, 160);

        btn_tim.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/timve.png"))); // NOI18N
        btn_tim.setText("TÌM");
        btn_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tim);
        btn_tim.setBounds(500, 310, 160, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("BACK");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 140, 34, 14);

        btn_back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ql.png"))); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(10, 40, 70, 140);

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset.png"))); // NOI18N
        btn_reset.setText("RESET");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset);
        btn_reset.setBounds(40, 250, 130, 39);

        btn_xoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xoa.png"))); // NOI18N
        btn_xoa.setText("XÓA");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_xoa);
        btn_xoa.setBounds(160, 480, 190, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Biển số");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 130, 110, 30);

        cbb_trangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoạt động", "Không hoạt động" }));
        jPanel1.add(cbb_trangthai);
        cbb_trangthai.setBounds(220, 180, 230, 40);

        btn_sua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-bao-hanh.png"))); // NOI18N
        btn_sua.setText("SỬA");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sua);
        btn_sua.setBounds(400, 480, 200, 60);
        jPanel1.add(txt_bienso);
        txt_bienso.setBounds(220, 130, 270, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Mã xe");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(110, 90, 110, 30);
        jPanel1.add(txt_ma);
        txt_ma.setBounds(220, 90, 270, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Xe Khách");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 30, 640, 44);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen2.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 30, 710, 280);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen3.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, -20, 720, 580);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen3.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, -20, 720, 580);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen1.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 0, 750, 510);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nen1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timActionPerformed

    private void tbl_xeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_xeMouseClicked
        int r = tbl_xe.getSelectedRow();
        if (r < 0) {
            return;
        }
        txt_ma.setText(tbl_xe.getValueAt(r, 0).toString());
        txt_bienso.setText(tbl_xe.getValueAt(r, 1).toString());      
        cbb_trangthai.setSelectedItem(tbl_xe.getValueAt(r, 2).toString());
        LoadImage(tbl_xe.getValueAt(r, 3).toString());
    }//GEN-LAST:event_tbl_xeMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, username, password);
            String sql = "insert into Xe values(?,?,?)\n";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, txt_bienso.getText());
            st.setString(2, cbb_trangthai.getSelectedItem().toString());
            st.setString(3, strHinhanh);          
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Thêm thông tin xe thành công");
            con.close();
            loadDataToTable();
        } catch (Exception e) {

            System.out.println(e);

        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_anhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anhActionPerformed
        try {
               JFileChooser choose=new JFileChooser("src\\IMG\\ImageXe");
                 int chon=choose.showOpenDialog(this);
                 File file = choose.getSelectedFile();
                 Image img = ImageIO.read(file);
                 strHinhanh = file.getName();
                 int width = btn_anh.getWidth();
                 int height= btn_anh.getHeight();
                 btn_anh.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
            }catch(Exception e){            
            }
    }//GEN-LAST:event_btn_anhActionPerformed

    private void btn_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timActionPerformed
         int i;
        String matx = txt_tim.getText();
        for (i = 0; i < list.size(); i++) {
            XeDAO xe = list.get(i);
            if (xe.MaXe.equals(matx) == true) {
                curredIndex = i;
                tbl_xe.setRowSelectionInterval(curredIndex, curredIndex);      
                DislayTX();
                break;
            }
        }
        if (i == list.size()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy xe");
        }
    }//GEN-LAST:event_btn_timActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Có",
                JOptionPane.YES_NO_OPTION);
        if (ret != JOptionPane.YES_OPTION) {
            return;
        }
        Connection c = null;
        PreparedStatement ps = null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            c = DriverManager.getConnection(url, username, password);
            ps = c.prepareStatement("Delete From Xe where MaXe = ?");
            ps.setString(1, txt_ma.getText());
            String ten = txt_bienso.getText();
            ret = ps.executeUpdate();
            if (ret != -1) {
                JOptionPane.showMessageDialog(this, "Đã xóa xe có biển số:  " + ten);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (c != null) {
                    c.close();
                }
                if (ps != null) {
                    ps.close();
                    loadDataToTable();
                    LoadData();
                }
            } catch (Exception ex2) {
                ex2.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, username, password);
            String sql = "update Xe set BienSo=?, TrangThai=?, HinhAnh=? where MaXe=?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, txt_bienso.getText());
            st.setString(2, cbb_trangthai.getSelectedItem().toString());
            st.setString(3, strHinhanh);        
            st.setString(4, txt_ma.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Sửa thông tin xe thành công");
            con.close();
            loadDataToTable();
            LoadData();

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
            TrangChu tc = new TrangChu();
            tc.setVisible(true);
            dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        txt_ma.setText("");
        txt_bienso.setText("");
        cbb_trangthai.setSelectedItem("");
        LoadImage("");
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Xe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Xe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Xe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Xe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Xe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anh;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_tim;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbb_trangthai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_xe;
    private javax.swing.JTextField txt_bienso;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_tim;
    // End of variables declaration//GEN-END:variables
}
